apiVersion: apps/v1
kind: Deployment
metadata:
  name: k3s-spring
  namespace: k3s
spec:
  # replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: k3s-spring
  template:
    metadata:
      labels:
        app: k3s-spring
    spec:
      containers:
        - name: k3s-spring
          image: hyunmok/k3s-spring:25.12.23
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "1300Mi"
            limits:
              cpu: "500m"
              memory: "1800Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: k3s-spring
  namespace: k3s
spec:
  type: NodePort
  selector:
    app: k3s-spring
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080